/** -*- mode: c++; coding: utf-8; -*- 
 *@file
 *@brief
 */
#ifndef GLOBUS_CXX_GRAM_PROTOCOL_HPP_
#define GLOBUS_CXX_GRAM_PROTOCOL_HPP_

#include "globus_gram_protocol_constants.h"

namespace globus { namespace gram { namespace protocol {

enum job_state
{
    JOB_STATE_PENDING = GLOBUS_GRAM_PROTOCOL_JOB_STATE_PENDING,
    JOB_STATE_ACTIVE = GLOBUS_GRAM_PROTOCOL_JOB_STATE_ACTIVE,
    JOB_STATE_FAILED = GLOBUS_GRAM_PROTOCOL_JOB_STATE_FAILED,
    JOB_STATE_DONE = GLOBUS_GRAM_PROTOCOL_JOB_STATE_DONE,
    JOB_STATE_SUSPENDED = GLOBUS_GRAM_PROTOCOL_JOB_STATE_SUSPENDED,
    JOB_STATE_UNSUBMITTED = GLOBUS_GRAM_PROTOCOL_JOB_STATE_UNSUBMITTED,
    JOB_STATE_STAGE_IN = GLOBUS_GRAM_PROTOCOL_JOB_STATE_STAGE_IN,
    JOB_STATE_STAGE_OUT = GLOBUS_GRAM_PROTOCOL_JOB_STATE_STAGE_OUT,
    JOB_STATE_ALL = GLOBUS_GRAM_PROTOCOL_JOB_STATE_ALL
};

}
}
}

#endif // GLOBUS_CXX_GRAM_PROTOCOL_HPP_
